USE [master]
GO

/****** Object:  Database [sigmasoftware]    Script Date: 12/8/2024 11:57:50 AM ******/
CREATE DATABASE [sigmasoftware]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'sigmasoftware', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\sigmasoftware.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'sigmasoftware_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\sigmasoftware_log.ldf' , SIZE = 8192KB , MAXSIZE = 102400KB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [sigmasoftware].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [sigmasoftware] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [sigmasoftware] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [sigmasoftware] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [sigmasoftware] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [sigmasoftware] SET ARITHABORT OFF 
GO

ALTER DATABASE [sigmasoftware] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [sigmasoftware] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [sigmasoftware] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [sigmasoftware] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [sigmasoftware] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [sigmasoftware] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [sigmasoftware] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [sigmasoftware] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [sigmasoftware] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [sigmasoftware] SET  DISABLE_BROKER 
GO

ALTER DATABASE [sigmasoftware] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [sigmasoftware] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [sigmasoftware] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [sigmasoftware] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [sigmasoftware] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [sigmasoftware] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [sigmasoftware] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [sigmasoftware] SET RECOVERY FULL 
GO

ALTER DATABASE [sigmasoftware] SET  MULTI_USER 
GO

ALTER DATABASE [sigmasoftware] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [sigmasoftware] SET DB_CHAINING OFF 
GO

ALTER DATABASE [sigmasoftware] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [sigmasoftware] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [sigmasoftware] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [sigmasoftware] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [sigmasoftware] SET QUERY_STORE = ON
GO

ALTER DATABASE [sigmasoftware] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [sigmasoftware] SET  READ_WRITE 
GO




CREATE TABLE [dbo].[Candidates](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](100) NOT NULL,
	[LastName] [nvarchar](100) NOT NULL,
	[Email] [nvarchar](255) NOT NULL,
	[PhoneNumber] [nvarchar](15) NULL,
	[CallTimeInterval] [nvarchar](50) NULL,
	[LinkedInUrl] [nvarchar](500) NULL,
	[GitHubUrl] [nvarchar](500) NULL,
	[Comment] [nvarchar](max) NOT NULL,
	[InterviewTime] [datetime] NULL,
	[SentEmail ] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[Candidates] ADD  DEFAULT ((0)) FOR [SentEmail ]

CREATE TABLE [dbo].[OnboardedCandidates](
	[TempEmployeeId] [int] IDENTITY(1,1) NOT NULL,
	[Email] [nvarchar](255) NOT NULL,
	[FullName] [nvarchar](200) NOT NULL,
	[OnboardedDate] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TempEmployeeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[OnboardedCandidates]  WITH CHECK ADD FOREIGN KEY([Email])
REFERENCES [dbo].[Candidates] ([Email])
